name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Rust Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Clippy Lint Check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # needed to post all lints as annotations for the pushed commit
          args: --all-features

      - uses: akhileshns/heroku-deploy@v3.5.7
        if: github.ref == 'refs/heads/master'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: graphql-pokeapi
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
